# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('projectRecordID', models.IntegerField(primary_key=True, serialize=False, verbose_name='Number: ')),
                ('goal', models.TextField()),
                ('owner', models.TextField()),
                ('group', models.TextField()),
                ('restrictedStatus', models.TextField()),
                ('startDate', models.DateField()),
                ('dueDate', models.DateField()),
                ('completionDate', models.DateField()),
                ('didNotMeetDate', models.DateField()),
                ('linkToMetrics', models.URLField()),
                ('deck', models.URLField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('comments', models.TextField()),
                ('executiveSummary', models.TextField()),
                ('definition', models.TextField()),
            ],
        ),
    ]
