# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formEntry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='formAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='createdDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
