# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formEntry', '0003_auto_20171106_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
