# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formEntry', '0006_auto_20171106_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectStatus',
            field=models.CharField(default='Green', max_length=6),
        ),
    ]
