# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formEntry', '0010_auto_20171113_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='editDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
