# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 20:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formEntry', '0011_project_editdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('projectRecordID', models.IntegerField(blank=True, db_index=True, verbose_name='Number: ')),
                ('goal', models.IntegerField()),
                ('owner', models.CharField(blank=True, max_length=128, null=True)),
                ('group', models.CharField(blank=True, max_length=128, null=True)),
                ('restrictedStatus', models.CharField(blank=True, max_length=128, null=True)),
                ('startDate', models.DateField()),
                ('dueDate', models.DateField()),
                ('revisedDueDate', models.DateField(blank=True, null=True)),
                ('completionDate', models.DateField(blank=True, null=True)),
                ('didNotMeetDate', models.DateField(blank=True, null=True)),
                ('projectStatus', models.CharField(default='Green', max_length=6)),
                ('linkToMetrics', models.URLField(blank=True, null=True)),
                ('deck', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('comments', models.CharField(blank=True, max_length=128, null=True)),
                ('executiveSummary', models.CharField(blank=True, max_length=128, null=True)),
                ('definition', models.CharField(blank=True, max_length=128, null=True)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('editDate', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical project',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatusIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectStatusIndicator', models.BooleanField(verbose_name='Project Status: ')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='definition',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='executiveSummary',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
