# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formEntry', '0012_auto_20171116_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='comments',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='definition',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='executiveSummary',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='definition',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='executiveSummary',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
