# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formEntry', '0013_auto_20171129_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectStatusIndicator',
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='projectCompletionStatus',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='projectCompletionStatus',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='goal',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='projectStatus',
            field=models.CharField(choices=[('Red', 'Red'), ('Yellow', 'Yellow'), ('Green', 'Green')], default='Green', max_length=6),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectStatus',
            field=models.CharField(choices=[('Red', 'Red'), ('Yellow', 'Yellow'), ('Green', 'Green')], default='Green', max_length=6),
        ),
    ]
