# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formEntry', '0014_auto_20171130_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='goal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.IntegerField(),
        ),
    ]
