# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formEntry', '0015_auto_20171130_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='pathToGreen',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='tags',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pathToGreen',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='goal',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.IntegerField(unique=True),
        ),
    ]
